batch_size: 23
constant_warmup: true
image_height: 384
image_width: 384
max_tokens: 50
model_pretrained_path: microsoft/trocr-small-handwritten
num_epochs: 50
num_images: null
num_workers: 9
print_eval_cer_every: 5
print_loss_every: 1
print_num_samples: 1
print_train_cer_every: 5
processor_pretrained_path: microsoft/trocr-small-handwritten
root_directory: home/jclar234/TrOCR
save_directory: null
save_every: 5
tokenizer_type: null
train: true
unfreeze: false
use_double: false
use_learned_position_embeddings: true
